## Verify the PyTorch install

In [8]:
import torch

In [9]:
print(torch.__version__)

1.7.0+cu101


In [10]:
import torchvision

In [11]:
print(torchvision.__version__)

0.8.1+cu101


In [12]:
torch.cuda.is_available()

False

In [13]:
torch.version.cuda

'10.1'

# CUDA Explained – Why Deep Learning Uses GPUs

In [14]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [ ]:
t = t.cuda()
t

In [16]:
assert type(t) == torch.Tensor

# Tensors Explained – Data Structures of Deep Learning

## Indexes

In [17]:
a = [1,2,3,4]

In [18]:
a[2]

3

In [19]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [20]:
dd[0][2]

3

In [21]:
assert dd[0][2] == 3

# Rank, Axes, and Shape Explained – Tensors for Deep Learning

## Rank

A tensor's *rank* tells us how many indexes are needed to refer to a specific element within the tensor.

## Axes

In [22]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [23]:
dd[0]

[1, 2, 3]

In [24]:
dd[1]

[4, 5, 6]

In [ ]:
dd[2]

[7, 8, 9]

The first index of axis 2:

In [25]:
dd[0][0]

1

In [26]:
dd[1][0]

4

In [27]:
dd[2][0]

7

The second index of axis 2:

In [28]:
dd[0][1]

2

In [29]:
dd[1][1]

5

In [30]:
dd[2][1]

8

The third index of axis 3:

In [31]:
dd[0][2]

3

In [32]:
dd[1][2]

6

In [33]:
dd[2][2]

9

## Shape

In [34]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [35]:
t = torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
type(t)

torch.Tensor

In [37]:
t.shape

torch.Size([3, 3])

A tensor's shape is important:

In [38]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [39]:
t.reshape(1,9).shape

torch.Size([1, 9])

In [40]:
assert t.reshape(1,9).shape == torch.Size([1,9])

# PyTorch Tensors Explained - Neural Network Programming

In [41]:
import torch
import numpy as np

## Tensor class

Tensors in PyTorch are represented using the ```torch.Tensor``` class. 

In [42]:
t = torch.Tensor()
type(t)

torch.Tensor

## Tensor attributes

In [43]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [ ]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [44]:
assert t.dtype == torch.float32

## Creation options using data

In [45]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [46]:
torch.Tensor(data) # class constructor

tensor([1., 2., 3.])

In [47]:
torch.tensor(data)

tensor([1, 2, 3])

In [48]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [49]:
torch.from_numpy(data)

tensor([1, 2, 3])

## Creation options without data

In [50]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [51]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [52]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [53]:
torch.rand(2,2)

tensor([[0.4163, 0.7529],
        [0.2378, 0.5718]])

# Creating PyTorch Tensors – Best Options

In [54]:
import torch
import numpy as np

In [55]:
data = np.array([1,2,3])

In [56]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data) # factory function
t3 = torch.as_tensor(data) # factory function
t4 = torch.from_numpy(data) # factory function

In [57]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [58]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int64
torch.int64
torch.int64


The constructor function used the default dtype.

In [59]:
torch.get_default_dtype()

torch.float32

In [ ]:
t1.dtype == torch.get_default_dtype()

True

In [60]:
assert t1.dtype == torch.get_default_dtype()

The factory functions infer the dtype.

In [61]:
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3])

In [ ]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

The dtype can be explicitly set.

In [62]:
torch.tensor(np.array([1,2,3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

## Memory: Sharing vs Copying

In [63]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [64]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [65]:
data[0] = 0
data[1] = 0
data[2] = 0

In [66]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3])


In [67]:
print(t3)
print(t4)

tensor([0, 0, 0])
tensor([0, 0, 0])


# Tensor Operations for Deep Learning

Operations by category:
- Reshaping ops
- Element-wise ops
- Reduction ops
- Access ops


# Reshaping Explained - PyTorch Tensors for Deep Learning

In [102]:
import torch

### Shape/Size of a tensor

In [86]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [87]:
t.size()

torch.Size([3, 4])

In [88]:
t.shape

torch.Size([3, 4])

In [89]:
len(t.shape)

2

In [90]:
torch.tensor(t.shape).prod()

tensor(12)

In [91]:
t.numel()

12

Since our tensor ```t``` has 12 elements, any reshaping must account for the number of elements (```12```). 

### Reshape/View

In [92]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [93]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [94]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [95]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [96]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [97]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

Reshaping and changing the rank.

In [98]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

### Squeeze/Unsqueeze

In [99]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [100]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [ ]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


Here is a use case for squeeze:

In [101]:
def flatten(t):
    t = t.reshape(1,-1) # t.reshape(-1)
    t = t.squeeze()
    return t

In [103]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

### Concantenate two tensors

In [104]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [105]:
torch.cat((t1, t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [106]:
torch.cat((t1, t2), dim=0).shape

torch.Size([4, 2])

In [107]:
torch.cat((t1, t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [108]:
torch.cat((t1, t2), dim=1).shape

torch.Size([2, 4])

# CNN Flatten Operation Visualized – Tensor Batch Processing for Deep Learning

In [110]:
import torch

In [111]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [112]:
t = torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 4, 4])

In [113]:
assert t.shape == torch.Size([3,4,4])

In [114]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

Add the color channel axis so we'll have: `(Batch size, Color channels, Height, Width)`

In [115]:
t = t.reshape(3,1,4,4)
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [116]:
t[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [117]:
t[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [118]:
t[0][0][0]

tensor([1, 1, 1, 1])

In [119]:
t[0][0][0][0]

tensor(1)

### Alternative implementations of the `flatten()`s function!

In [122]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [123]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [125]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [126]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [127]:
t.reshape(1,-1).squeeze()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

### Only Flatten the last 3 axes

In [128]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [129]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [133]:
t.reshape(3,-1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

# Element-wise tensor operations - Deep Learning and Neural Networks

Element-wise means that we operate on corresponding elements.  
Two elements are said to corresponding if the two elements occupy the same position within the tensor.  
The position is determined by the indexes used to specify a given element.

In [134]:
import torch
import numpy as np

In [135]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)

In [136]:
# Example from the first axis
t1[0]

tensor([1., 2.])

In [137]:
# Example from the second axis
t1[0][0]

tensor(1.)

In [138]:
t1[0][0]

tensor(1.)

In [139]:
t2[0][0]

tensor(9.)

### Addition is an element-wise operation

In [140]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

### Arithmetic operations are element-wise operations

Let's see how we can add scalar values to tensors:

In [141]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [142]:
t1 - 2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [143]:
t1 * 2

tensor([[2., 4.],
        [6., 8.]])

In [144]:
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [145]:
t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [146]:
t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [147]:
t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [148]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

These examples make it look like element-wise means *for each element*.  
However, this is misleading.  
A concept called broadcasting is being used here.

#### Broadcasting tensors

What is really happening in ```t1 + 2``` is that the scaler ```2``` is being broadcasted to the shape of ```t1```.  
This can be done using Numpy like this:

In [149]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

After the new tensor is created from the broadcast operation, the element-wise addition is performed.  
So this:

In [150]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

is really this:

In [151]:
t1 + torch.tensor(
    np.broadcast_to(2, t1.shape)
    ,dtype=torch.float32
)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141.)
  This is separate from the ipykernel package so we can avoid doing imports until


tensor([[3., 4.],
        [5., 6.]])

Trickier example:

In [152]:
t1 = torch.tensor([
    [1,1],
    [1,1]
], dtype=torch.float32)

t2 = torch.tensor([2,4], dtype=torch.float32)

In [153]:
# t1 + t2 ???????

In [154]:
t1.shape

torch.Size([2, 2])

In [155]:
t2.shape

torch.Size([2])

In [156]:
np.broadcast_to(t2.numpy(), t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [157]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

### Element-wise comparison operations

In [158]:
import torch

In [159]:
t = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

In [160]:
t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [161]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [162]:
t.gt(0)

tensor([[False,  True,  True],
        [ True, False,  True],
        [False,  True, False]])

In [163]:
t.lt(0)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [164]:
t.le(7)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

Thinking about these types of operations from a broadcasting perspective, we can see that ```t.le(7)``` is the same thing as:

In [167]:
t <= torch.tensor(
    np.broadcast_to(7, t.shape)
    ,dtype=torch.float32
)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

and this:

In [168]:
t <= torch.tensor([
    [7,7,7],
    [7,7,7],
    [7,7,7]
], dtype=torch.float32)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

### [BC-BREAKING] Changed tensor comparison return type from uint8 to bool #21113

Relevant links:  
https://github.com/pytorch/pytorch/pull/21113  
https://github.com/pytorch/pytorch/releases/tag/v1.2.0

This change was introduced in PyTorch version 1.2.0.  
Unit test for this change is below:

In [169]:
# Unit test
t1 = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

t2 = torch.tensor([
    [7,7,7],
    [7,7,7],
    [7,7,7]
], dtype=torch.float32)

t3 = t1 <= t2

assert t3.dtype == torch.bool

### Element-wise operations using functions

In [170]:
t.abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [171]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [172]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [173]:
torch.tensor([-0.0])

tensor([-0.])

In [174]:
torch.tensor([0])

tensor([0])

In [175]:
torch.tensor([0]).neg()

tensor([0])

In [176]:
-0.0

-0.0

In [177]:
t.neg().abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

# Argmax and Reduction Ops - Tensors for Deep Learning

In [178]:
import torch
import numpy as np

A tensor *reduction operation* is an operation that reduces the number of elements contained within a given tensor. 

Suppose we have the following tensor:

In [179]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

Observe that the sum function returns the sum of all the elements in the tensor:

In [180]:
t.sum()

tensor(8.)

In [181]:
t.numel()

9

In [182]:
t.sum().numel()

1

In [183]:
t.sum().numel() < t.numel()

True

In [184]:
assert t.sum().numel() < t.numel()

Therefore, we can conclude that the ```sum()``` function is a reduction operation.

### Common reduction operations

In [185]:
t.sum()

tensor(8.)

In [186]:
t.prod()

tensor(0.)

In [187]:
t.mean()

tensor(0.8889)

In [188]:
t.std()

tensor(1.1667)

### Reduce specific axes

In [189]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [190]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [191]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

Element-wise opeartions are in play here:

In [192]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [193]:
t[0]

tensor([1., 1., 1., 1.])

In [194]:
t[1]

tensor([2., 2., 2., 2.])

In [195]:
t[2]

tensor([3., 3., 3., 3.])

In [196]:
t[0] + t[1] + t[2]

tensor([6., 6., 6., 6.])

Three groups of four:

In [197]:
t[0].sum()

tensor(4.)

In [198]:
t[1].sum()

tensor(8.)

In [199]:
t[2].sum()

tensor(12.)

In [200]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

### Max/Argmax

In [214]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [215]:
t.max()

tensor(5.)

In [216]:
t.argmax()

tensor(11)

In [217]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

If we specify a dimension, the ```max()``` function will return two tensors.  

In [218]:
t.max(dim=0)

torch.return_types.max(values=tensor([4., 3., 3., 5.]), indices=tensor([2, 1, 1, 2]))

In [219]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [220]:
t.max(dim=1)

torch.return_types.max(values=tensor([2., 3., 5.]), indices=tensor([3, 1, 3]))

In [221]:
t.argmax(dim=1)

tensor([3, 1, 3])

## Accessing operations

In [222]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32) ## Accessing operations

In [223]:
t.mean()

tensor(5.)

In [211]:
t.mean().item()

5.0

In [224]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [225]:
t.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)

In [226]:
assert t.mean().item() == 5